name: Deploy to RunPod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/photo2model-service:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/photo2model-service:latest

      - name: Deploy to RunPod
        run: |
          curl -X POST https://api.runpod.io/graphql \
            -H "Authorization: Bearer ${{ secrets.RUNPOD_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "query": "mutation { podFindAndDeploy(input: { templateId: /"dm0rb50ecd/", imageName: \"${{ secrets.DOCKER_USERNAME }}/photo2model-service:latest\" }) { id }}"}'
